export const FlightRouteInfo = [
    {
        id: 1,
        flightNo: 'EK500',
        departureDate: 'Mon 27 Sep',
        departureTime: '08:00',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '11:05',
        duration: '3 hrs 5mins',
        origin: 'Dubai (DXB)',
        destination: 'Mumbai (BOM)',
        aircraft: 'B777',
    },
    {
        id: 2,
        flightNo: 'EK201',
        departureDate: 'Mon 27 Sep',
        departureTime: '08:30',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '13:55',
        duration: '14 hrs 25mins',
        origin: 'Dubai (DXB)',
        destination: 'New York (JFK)',
        aircraft: 'A380',
    },
    {
        id: 3,
        flightNo: 'EK003',
        departureDate: 'Mon 27 Sep',
        departureTime: '14:30',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '18:20',
        duration: '7 hrs 50mins',
        origin: 'Dubai (DXB)',
        destination: 'London Heathrow (LHR)',
        aircraft: 'A380',
    },
    {
        id: 4,
        flightNo: 'EK408',
        departureDate: 'Mon 27 Sep',
        departureTime: '03:00',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '23:20',
        duration: '13 hrs 20mins',
        origin: 'Dubai (DXB)',
        destination: 'Melbourne (MEL)',
        aircraft: 'B777',
    },
    {
        id: 5,
        flightNo: 'EK087',
        departureDate: 'Mon 27 Sep',
        departureTime: '08:25',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '12:25',
        duration: '7 hrs 0mins',
        origin: 'Dubai (DXB)',
        destination: 'Zurich (ZRH)',
        aircraft: 'A380',
    },
    {
        id: 6,
        flightNo: 'EK761',
        departureDate: 'Mon 27 Sep',
        departureTime: '04:40',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '10:55',
        duration: '8 hrs 15mins',
        origin: 'Dubai (DXB)',
        destination: 'Johannesburg (JNB)',
        aircraft: 'A380',
    },
    {
        id: 7,
        flightNo: 'EK373',
        departureDate: 'Mon 27 Sep',
        departureTime: '20:35',
        arrivalDate: 'Tue 28 Sep',
        arrivalTime: '00:50',
        duration: '7 hrs 15mins',
        origin: 'Dubai (DXB)',
        destination: 'Bangkok (BKK)',
        aircraft: 'B777',
    },
    {
        id: 8,
        flightNo: 'EK334',
        departureDate: 'Mon 27 Sep',
        departureTime: '09:25',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '21:35',
        duration: '8 hrs 10mins',
        origin: 'Dubai (DXB)',
        destination: 'Manila (MNL)',
        aircraft: 'B777',
    },
    {
        id: 9,
        flightNo: 'EK722',
        departureDate: 'Mon 27 Sep',
        departureTime: '23:55',
        arrivalDate: 'Tue 28 Sep',
        arrivalTime: '05:55',
        duration: '5 hrs 0mins',
        origin: 'Dubai (DXB)',
        destination: 'Nairobi (NBO)',
        aircraft: 'B777',
    },
    {
        id: 10,
        flightNo: 'EK801',
        departureDate: 'Mon 27 Sep',
        departureTime: '00:15',
        arrivalDate: 'Mon 27 Sep',
        arrivalTime: '02:10',
        duration: '2 hrs 55mins',
        origin: 'Dubai (DXB)',
        destination: 'Jeddah (JED)',
        aircraft: 'B777',
    },
];